parameters:
    #identifiants db
    driver:  mysql
    host:  localhost
    username:  root
    password:  s3curit3
    database: site
    charset:  utf8
    collation:  utf8_unicode_ci
    prefix: ~
    #php slim errors
    displayErrorDetails:  false
